config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, expect:[:show]
  get "portfolio/:id", to: "portfolios#show", as: "portfolio_show" #as is used to customize the prefix
  # get "pages/home"
  get "about", to:"pages#about"
  get "contact", to:  "pages#contact"

  get "ruby-items", to:"portfolios#ruby"

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank?}

    include Placeholder
    validates_presence_of :title, :body


    def self.react
        where(subtitle:"React")
    end

    scope :ruby, -> {where(subtitle:"Ruby on Rails")}

    after_initialize :set_defaults

    def set_defaults
        self.main_image ||= Placeholder.image_generator(height:'600', width:'400')
        self.thumb_image ||= Placeholder.image_generator(height:'350', width:'200')
      end
      
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource


    def index
        @portfolio_items = Portfolio.all
    end

    def ruby 
        @portfolio_ruby_items = Portfolio.ruby
    end

    def new
        @portfolio_item = Portfolio.new
        3.times {@portfolio_item.technologies.build}
    end

    def edit
     @portfolio
    end

    def show
        @portfolio
    end

    def create
        @portfolio_item = Portfolio.new( params.require(:portfolio).permit(:title, :subtitle,:body, technologies_attributes: [:name]))
        @portfolio_item.set_defaults

        respond_to do |format|
            if @portfolio_item.save
                format.html {redirect_to portfolios_path, notice: "Portfolio item was successfully created."}
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def update
        @portfolio
        respond_to do |format|
            if @portfolio.update(params.require(:portfolio).permit(:title, :subtitle,:body))
                format.html { redirect_to portfolios_path, notice: "Record was successfully updated." }
            else
                format.html { render :edit, status: :unprocessable_entity }
            end
        end

    end

    def destroy
        @portfolio
        @portfolio.destroy

        respond_to do |format|
            format.html {redirect_to portfolios_path}
        end

    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio Item</h1>

<%= form_for(@portfolio) do |f| %>
    <div class= "field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>

    <div class= "field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
    </div>

    <div class= "field">
    <%= f.label :body %>
    <%= f.text_area :body %>
    </div>

    <div class= "actions">
    <%= f.submit%>
    </div>

<% end %>

app/views/portfolios/index.html.erb
<h1> Portfolio Items</h1>

<a href = "portfolios/new">Create New Item</a>

<% @portfolio_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
    <p><%= portfolio_item.subtitle%></p>
    <p><%= portfolio_item.body%></p>
    <%=image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
    <%= button_to "Delete", portfolio_path(portfolio_item.id), method: :delete%>

<% end %>

app/views/portfolios/new.html.erb
<h1>Create a New Portfolio Item</h1>

<%= form_for(@portfolio_item) do |f| %>
    <div class= "field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>

    <div class= "field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
    </div>

    <div class= "field">
    <%= f.label :body %>
    <%= f.text_area :body %>
    </div>

    <ul>
    <%= f.fields_for :technologies do |technology_form| %>
    <li>
    <%= technology_form.label :name %>
    <%= technology_form.text_field :name %>
    </li>
    <% end %>
    </ul>

    <div class= "actions">
    <%= f.submit%>
    </div>

<% end %>

app/views/portfolios/ruby.html.erb
<h1> Portfolio Ruby Items</h1>

<a href = "portfolios/new">Create New Item</a>

<% @portfolio_ruby_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
    <p><%= portfolio_item.subtitle%></p>
    <p><%= portfolio_item.body%></p>
    <%=image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
    <%= button_to "Delete", portfolio_path(portfolio_item.id), method: :delete%>

<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio.main_image if !@portfolio.main_image.nil? %>
<h1><%= @portfolio.title%></h1>
<em><%= @portfolio.subtitle%></em>
<p><%= @portfolio.body%></p>


<h1>Technologies Used</h1>
<% @portfolio.technologies.each do |t|%>
<p><%= t.name%></p>
<%end%>