config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, expect:[:show]
  get "portfolio/:id", to: "portfolios#show", as: "portfolio_show" #as is used to customize the prefix
  # get "pages/home"
  get "about", to:"pages#about"
  get "contact", to:  "pages#contact"

  get "ruby-items", to:"portfolios#ruby"

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Devcamp Portfolio" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div>
    <div><%= link_to 'Home', root_path %></div>
    <div><%= link_to 'About', about_path %></div>
    <div><%= link_to 'Contact', contact_path %></div>
    <div><%= link_to 'Blog', blogs_path %></div>
    <div><%= link_to 'Portfolio', portfolios_path %></div>
  </div>
    <% if current_user.is_a?(GuestUser) %>
      <%= link_to 'register', new_user_registration_path %>
      <%= link_to 'login', new_user_session_path %>
    <% else %>
      <%= button_to 'logout', destroy_user_session_path , method: :delete%>
    <% end %>
    <%= yield %>
    <% if session[:source] %>
    <p>Thanks for visiting me from <%= session[:source]%></p>
    <% end %>
  </body>
</html>